---
- name: Create Node Exporter directory
  ansible.builtin.file:
    path: "{{ node_exporter_dir }}"
    state: directory
    owner: root
    group: root

- name: Download Node Exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz

- name: Extract Node Exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: "{{ node_exporter_dir }}"
    remote_src: yes

- name: Create systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      ExecStart={{ node_exporter_dir }}/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Start Node Exporter service
  ansible.builtin.systemd:
    name: node_exporter
    enabled: yes
    state: started
