---
- name: Update apt/yum packages
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Install common dependencies (skip curl as it conflicts with curl-minimal on Amazon Linux)
  ansible.builtin.package:
    name:
      - tar
      - wget
      - unzip
      - python3
      - python3-pip
    state: present
