# 全局变量
prometheus_version: "2.53.0"
node_exporter_version: "1.8.1"
grafana_version: "11.0.0"

prometheus_dir: /opt/prometheus
node_exporter_dir: /opt/node_exporter
grafana_dir: /opt/grafana

# Prometheus配置
prometheus_scrape_interval: 15s
prometheus_targets:
  - localhost:9100

# Grafana配置
grafana_admin_user: admin
grafana_admin_password: admin
